### ISSUE TITLE
Considered trying to get this in to golint or `go vet`?

### ISSUE THREAD

**Issue by JensRantil** [dominikh/go-staticcheck#2]
Just curious, have you considered trying to get this in to golint or `go vet`? Why or why not?

**Comment by dominikh** [comment]
By "this" do you mean every check? Most of the checks in here were rejected from `go vet` or don't quite fit. And golint is a poor choice because it is about following established style, not finding bugs.

`go vet` is interested in checking code that compiles, works without crashing but is subtly wrong. staticcheck, on the other hand, is interested in checking code before it's ever run.
- The regexp check was once considered for go vet, but then rejected because of the above reason
- There's an open issue for checking time.Format – if that ever makes it into go vet, we'll likely remove it from staticcheck. There hasn't been any discussion about its suitability yet.
- The time.Sleep check was once considered for go vet, then for go lint, but rejected because they tried to make it too general, and ran into too many false positives
- The template parsing probably falls into the same category as regexp
- The waitgroup checks might fit into go vet. I have no interest in upstreaming them at this point, however. Someone else is of course free to do so.

**Comment by JensRantil** [comment]
Cool. Thanks for an exhaustive answer!
