### ISSUE TITLE
fmt.Errorf with no formatting arguments - should use errors.New instead

### ISSUE THREAD

**Issue by kevinburke** [dominikh/go-staticcheck#24]
If I do e.g. `return fmt.Errorf("Invalid value")`, I'll invoke the fmt package and interpolation even though it's simpler/faster to call `errors.New("Invalid value")`.

**Comment by dgryski** [comment]
`golint` catches the similar case of using `errors.New(fmt.Sprintf(...))` instead of `fmt.Errorf()`.  I suppose this is going the other way.  Possbily this belongs under `gosimple` and not `staticcheck` ?

**Comment by dominikh** [comment]
We flag the Printf family of functions in fmt and log when the first argument is a dynamic string, and no other arguments are provided. We should do the same for Errorf.

We do not flag constant strings in this case because there is less risk of bad output.

Suggesting errors.New instead of fmt.Errorf would indeed belong in gosimple, but it's not a good suggestion to make. While faster and simpler in general, speed does not matter for the error path, and it stops being simpler when one already imports fmt but hasn't imported errors yet.
