### ISSUE TITLE
Consider flagging signal.Notify(..., os.Kill, ...)

### ISSUE THREAD

**Issue by dominikh** [dominikh/go-staticcheck#26]
os.Kill (syscall.SIGKILL) cannot be trapped or ignored. As such, its presence in signal.Notify is ineffective. The Go documentation used to contain an example using it that way, which explains why ~16% of all signal.Notify calls include os.Kill. 

This isn't a very important check. As long as os.Kill isn't the only argument in the list, it's not really doing any harm.

**Comment by judwhite** [comment]
> This isn't a very important check. As long as os.Kill isn't the only argument in the list, it's not really doing any harm.

@dominikh @bradleyfalzon The process will exit if it receives `SIGTERM` whether or not it's specified in `signal.Notify`. If you're expecting behavior on `SIGTERM` and the process just exits, that's at least as harmful as `kill -9` when you intended to `kill`.

**Comment by bradleyfalzon** [comment]
As discussed, I'm not having any issues catching (https://play.golang.org/p/wthajeuXBJ) or ignoring (https://play.golang.org/p/NIr68-TBck) SIGTERM (sent to test program called signals `killall -SIGTERM signals`)

EDIT: sorry, misunderstood, you weren't saying sigterm can't be caught, ignore my comment.

**Comment by judwhite** [comment]
To clarify, in nearly every case where the projects found by @dominikh's tool use `signal.Notify(c, os.Interrupt, os.Kill)` the intention was `signal.Notify(c, os.Interrupt, syscall.SIGTERM)` (or, `signal.Notify(c, syscall.SIGINT, syscall.SIGTERM)`, or `signal.Notify(c, os.Interrupt os.Signal(syscall.SIGTERM))`, depending on your preference). The only exception to it being flat wrong is where the code was asking for `os.Kill` _and_ `syscall.SIGTERM`. `syscall.SIGTERM` is technically not portable because it doesn't exist on every target platform, but `linux`, `darwin`, `freebsd`, `windows` do support it.

There are [additional signals](https://github.com/golang/go/issues/8953) which can't be caught, but they're probably not as prevalent. A quick check should be possible.

In addition to calling out `os.Kill`, because of [the documentation issue](https://github.com/golang/go/issues/13080), it may be helpful for `staticcheck` to suggest `syscall.SIGTERM` in its place.

**Comment by bradleyfalzon** [comment]
I left the check generic enough to detect other signals, but couldn't find a definitive list of signals that cannot be caught (other than https://en.wikipedia.org/wiki/Unix_signal#POSIX_signals which only says SIGKILL and SIGSTOP cannot be caught). If there are other signals that cannot be caught across all platforms, I think it's a good idea to add them. As for `syscall.SIGCONT` and `syscall. SIGTSTP`, I was able to catch them in some tests https://play.golang.org/p/VC39veq552)

As for suggesting `syscall.SIGTERM` instead in the error message, I understand, but I'm not certain whether we want to suggest something that isn't portable though?

**Comment by judwhite** [comment]
> As for suggesting `syscall.SIGTERM` instead in the error message, I understand, but I'm not certain whether we want to suggest something that isn't portable though?

I understand the portability concern, but literally every instance found on GitHub where `os.Kill` was used they meant to handle `syscall.SIGTERM`. It's just a suggestion and has a high likelihood of being helpful. I'll defer, I've made my position known ¯\\_(ツ)_/¯

**Comment by dominikh** [comment]
When the untrappable signal is `os.Kill`, append `(did you mean syscall.SIGTERM?)` to the error message, otherwise don't.

**Comment by bradleyfalzon** [comment]
OK, I have a local commits with this change. I'll push later.
