### ISSUE TITLE
SA2002 (T.Fatal called in non-main goroutine) can be fooled by depth

### ISSUE THREAD

**Issue by tamird** [dominikh/go-staticcheck#60]
SA2002 correctly detects calls to T.Fatal when they occur in the "main" function of the non-main goroutine, but if these calls occur further down the call stack, they are not detected. In particular, https://github.com/cockroachdb/cockroach/pull/12183/commits/beabaa28bac27820d4ff99a6eed081f7f395a72b#diff-8baee8c977f171cd6d50a3c72d681f3fR258 caused the call to T.Fatal to be detected, though it was present before this commit as well, only deeper in the call stack.

**Comment by dominikh** [comment]
Yeah, that is to be expected. We do only check the immediately called function, and not the entire call tree rooted at the goroutine. 

I haven't given any thought to possible complications with doing so (other than speed concerns), but it's also not a high priority, because the majority of cases are matched by the current check.

I'll leave the issue open to track the possible improvement to SA2002.
