### ISSUE TITLE
detect math.Pow() with small positive constants

### ISSUE THREAD

**Issue by dgryski** [dominikh/go-staticcheck#63]
https://github.com/golang/go/issues/7416

`math.Pow(x,1)`, and `math.Pow(x,2)` should definitely be flagged.

`math.Pow(x,3)` and `math.Pow(x,4)` maybe ?

Where to draw the line?

**Comment by dominikh** [comment]
Probably a candidate for gosimple rather than staticcheck. While `x^1` is pointless, it's probably not harmful. `x^2` is very obviously meant as a simplification. As for the line: I'd argue in favour of  `x^2`. Nobody (heh, right…) will argue that `math.Pow(x, 2)` is simpler or clearer than `x*x`. For >2, people will have all kinds of opinions.

**Comment by dgryski** [comment]
Could also be determined by benchmarking where the performance cutoff switches over.

**Comment by dominikh** [comment]
I am less concerned about performance and more about readability. is `x*x*x*x` better than `math.Pow(x, 4)` just because it is slightly faster?

**Comment by dmitshur** [comment]
> Nobody (heh, right…) will argue that `math.Pow(x, 2)` is simpler or clearer than `x*x`.

Context matters, and I expect in some (rare) cases, the context will dictate which of the two styles is more appropriate. I don't think you can make a blanket statement that applies in all cases.

Same goes for `errors.New` vs `fmt.Errorf`, `fmt.Println` vs `fmt.Printf`, etc.
